### ISSUE TITLE
tuftool: Support binary releases on Github

### ISSUE THREAD

**Issue by cbgbt** [awslabs/tough#662]
What I'd Like:
I'd like to be able to install pre-built binaries of tuftool.

```[tasklist]
### Tasks
- [ ] Support binary releases on Linux for x86_64/arm64
- [ ] https://github.com/awslabs/tough/issues/349
- [ ] Support binary releases on Windows for x86_64
- [ ] https://github.com/awslabs/tough/issues/663
- [ ] Support binary releases on MacOS for x86_64/arm64
```

I'm not totally committed to that list of platforms and architectures. I'll keep this issue updated as I continue to do some research.

**Comment by mikn** [comment]
Is something missing to move this along? I am swift approaching the same point that others were in when they asked for this and would love if I could just download the tuftool binary to manage the bottlerocket images rather than building from source. I would prefer not to use the Docker image as binaries integrate better with our dependency management systems.

**Comment by jku** [comment]
> I'd like to be able to install pre-built binaries of tuftool.

I'll mention https://github.com/PyO3/maturin here: it's a pretty cheeky way to achieve not only binary packaging but also a robust delivery mechanism: It creates thin Python wrappers for your rust binaries and uploads them to pypi.org.

https://github.com/woodruffw/zizmor is an example of a rust app that can be installed in seconds with `pip install zizmor`: I believe the only things needed in zizmor sources are one GH workflow and a pyproject.toml file
